# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e61e9278dc59491f27ff4a87d1c92aa83b5590694f4fdea5bad81e1877b67802491d7ae2a3ad10e0b66032ec264f53d24a01ae9fab3823ce77a014c8e93728f
  facebook_app_id: 873794626038123
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 90c5f3d45d112848e5696e258c773a78d974c4b573628bbcafe84d2c4f8bf831f426657b9a1badbe15ef620cd9383c1ddadac32e1a677c06f5b9daa972248520
  facebook_app_id: 873794626038123
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 873794626038123
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
